{% set name = "ez_setup" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 303c5b17d552d1e3fb0505d80549f8579f557e13d8dc90e5ecef3c07d7f58642

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  import:
    - ez_setup

about:
  home: https://code.activestate.com/pypm/ez-setup/
  license: MIT
  license_family: MIT
  summary: 'ez_setup.py and distribute_setup.py'
  dev_url: https://github.com/ActiveState/ez_setup

extra:
  recipe-maintainers:
    - pmlandwehr
